### ISSUE TITLE
bhaee stream

### ISSUE THREAD

**Issue by KillerDogeEmpire** [mxbhaee/bhaee-stream#2]
This is just a copy of CloudStream. You don't even give any credit to the actual devs

**Comment by mxbhaee** [comment]
am working on crediting them

**Comment by ghost** [comment]
Ok. Sorry for being rude it's just I am a fan of cs3 and have helped contribute to it so it's good to hear your going to credit them

**Comment by mxbhaee** [comment]
Have checked the code and its absolutely amazing . I respect the art in code one puts in , very amazing . hope to contribute better back too . Maybe if your interested in partnership on a project idea I have I would be honored to work hand in hand with you .
The project idea is a fintech that combines all currents in just clicks of a few buttons . I have a start up company that am trying to raise to appoint . If your interested at all  my contacts are bhaee@bhaeecorp.com or telegram https://t.me/mxbhaee or whatsApp +256708476565

**Comment by ghost** [comment]
I have made an email.
(May not be sent when I have posted this comment)
